import { useState, useEffect } from 'react';
import {
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from '@/components/ui/card';
import { DashboardCard } from '@/components/dashboard-card';
import { Compass, Sparkles, Activity } from 'lucide-react';
import { getAdminActivity } from '@/services/adminService';

export function DashboardActivity() {
  const [activities, setActivities] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadActivities = async () => {
      try {
        const res = await getAdminActivity();
        if (res.data && res.data.length > 0) {
          setActivities(
            res.data.map((item) => ({
              title: item.title,
              time: item.time ? new Date(item.time).toLocaleDateString() : 'Just now',
              icon: <Sparkles className="size-4 text-orange-400" />
            }))
          );
        } else {
          setActivities([]);
        }
      } catch {
        setActivities([]);
      } finally {
        setLoading(false);
      }
    };
    loadActivities();
    const interval = setInterval(loadActivities, 12000);
    return () => clearInterval(interval);
  }, []);

  return (
    <DashboardCard className="gap-0">
      <CardHeader className="border-b">
        <CardTitle>Traveler & AI Activity</CardTitle>
        <CardDescription>Live real-time feed across WanderSync platform.</CardDescription>
      </CardHeader>
      <CardContent className="px-0">
        {loading ? (
          <div className="py-8 text-center text-xs text-muted-foreground">
            Loading telemetry feed...
          </div>
        ) : activities.length === 0 ? (
          <div className="py-8 text-center space-y-1.5 px-4">
            <Activity className="size-6 text-muted-foreground mx-auto" />
            <p className="text-xs font-bold text-foreground">No Activity Telemetry Yet</p>
            <p className="text-[11px] text-muted-foreground">
              New itineraries generated by travelers will stream in real-time here.
            </p>
          </div>
        ) : (
          <ul className="flex flex-col divide-y divide-border">
            {activities.map((item, index) => (
              <li className="flex h-14 items-center gap-3 px-5" key={index}>
                <span
                  aria-hidden="true"
                  className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-secondary border border-border"
                >
                  {item.icon}
                </span>
                <div className="min-w-0 flex-1 space-y-0.5">
                  <p className="line-clamp-1 text-foreground text-xs font-semibold leading-snug">
                    {item.title}
                  </p>
                  <p className="text-muted-foreground text-[10px] font-mono">{item.time}</p>
                </div>
              </li>
            ))}
          </ul>
        )}
      </CardContent>
    </DashboardCard>
  );
}
