import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import {
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from '@/components/ui/table';
import { DashboardCard } from '@/components/dashboard-card';
import { ArrowRightIcon, MapPin, Compass } from 'lucide-react';
import { getAdminRecentTrips } from '@/services/adminService';

export function DashboardInvoices() {
  const [trips, setTrips] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadTrips = async () => {
      try {
        const res = await getAdminRecentTrips();
        if (res.data && res.data.length > 0) {
          setTrips(
            res.data.map((t) => ({
              id: t._id.slice(-6).toUpperCase(),
              destination: `${t.destination?.city || 'City'}, ${t.destination?.country || 'Destination'}`,
              days: `${t.durationDays || 3} Days`,
              budget: `$${t.estimatedTotalCost || 1200}`
            }))
          );
        } else {
          setTrips([]);
        }
      } catch {
        setTrips([]);
      } finally {
        setLoading(false);
      }
    };
    loadTrips();
    const interval = setInterval(loadTrips, 12000);
    return () => clearInterval(interval);
  }, []);

  return (
    <DashboardCard className="relative gap-0 md:col-span-2">
      <CardHeader className="border-b">
        <CardTitle className="text-base">Recent AI Generated Itineraries</CardTitle>
        <CardDescription>Live real-time feed of trips generated by Gemini Maestro.</CardDescription>
      </CardHeader>
      <CardContent className="px-0">
        {loading ? (
          <div className="py-8 text-center text-xs text-muted-foreground">
            Loading recent trips...
          </div>
        ) : trips.length === 0 ? (
          <div className="py-8 text-center space-y-1.5 px-4">
            <Compass className="size-6 text-muted-foreground mx-auto" />
            <p className="text-xs font-bold text-foreground">No Itineraries Generated Yet</p>
            <p className="text-[11px] text-muted-foreground">
              When travelers create AI travel plans, they will appear in this live table.
            </p>
          </div>
        ) : (
          <Table>
            <TableCaption className="sr-only">
              Recent itineraries with destination, duration, budget, and status.
            </TableCaption>
            <TableHeader>
              <TableRow>
                <TableHead className="ps-6">Destination</TableHead>
                <TableHead>Trip ID</TableHead>
                <TableHead>Duration</TableHead>
                <TableHead className="pe-6 text-right tabular-nums">Est. Budget</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {trips.map((trip) => (
                <TableRow className="h-12 hover:bg-secondary/40 transition-colors" key={trip.id}>
                  <TableCell className="max-w-40 truncate ps-6 font-medium flex items-center gap-2">
                    <MapPin className="size-3.5 text-orange-400 shrink-0" />
                    <span className="truncate">{trip.destination}</span>
                  </TableCell>
                  <TableCell className="text-muted-foreground font-mono text-xs">
                    #{trip.id}
                  </TableCell>
                  <TableCell className="text-muted-foreground text-xs">
                    {trip.days}
                  </TableCell>
                  <TableCell className="pe-6 text-right tabular-nums font-semibold text-foreground">
                    {trip.budget}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        )}
      </CardContent>
      {trips.length > 0 && (
        <div className="border-t border-border/70 p-2 flex items-center justify-center bg-background">
          <Link
            to="/admin/trips"
            className="inline-flex items-center gap-1 text-xs font-semibold text-muted-foreground hover:text-foreground transition-colors cursor-pointer py-1 px-3 rounded-lg hover:bg-secondary"
          >
            <span>View All Trips</span>
            <ArrowRightIcon aria-hidden="true" className="size-3.5" />
          </Link>
        </div>
      )}
    </DashboardCard>
  );
}
