import { useNavigate } from 'react-router-dom';
import { Sparkles, Users, Compass, Star, ArrowRight } from 'lucide-react';

const stories = [
  {
    author: 'Elena Vance',
    role: 'Solo Adventurer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    title: '7 Days in Tokyo & Hakone',
    quote: 'WanderSync mapped out off-the-beaten-path matcha tea houses and scenic cable car routes that I would have never found alone.',
    rating: 5,
    likes: '1.2k'
  },
  {
    author: 'Marcus Sterling',
    role: 'Digital Nomad',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    title: '14 Days Along the Amalfi Coast',
    quote: 'The live weather telemetry and offline PDF export kept our group perfectly on schedule even when coastal cell reception dropped.',
    rating: 5,
    likes: '980'
  },
  {
    author: 'Aria Takahashi',
    role: 'Photographer',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80',
    title: '5 Days in Iceland Glacier Lagoons',
    quote: 'The AI tailored morning golden-hour photo spots with zero tourist crowds. Absolute game changer.',
    rating: 5,
    likes: '2.4k'
  }
];

export default function Community() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-[#09090b] text-[#fafafa] py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-6xl mx-auto space-y-16">
        <div className="text-center space-y-4">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full liquid-glass border border-cyan-500/30 text-cyan-400 text-xs font-semibold uppercase tracking-wider">
            <Users className="size-3.5" />
            Global Creators & Explorers
          </div>
          <h1 className="text-4xl sm:text-6xl font-normal font-['Instrument_Serif'] tracking-tight">
            Curated by Travelers, Powered by AI
          </h1>
          <p className="text-sm sm:text-base text-muted-foreground max-w-2xl mx-auto font-sans leading-relaxed">
            Discover bespoke itineraries generated by creators and wanderers worldwide.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {stories.map((s) => (
            <div
              key={s.author}
              className="p-6 rounded-2xl liquid-glass-card border border-border/80 flex flex-col justify-between space-y-6 hover:border-cyan-500/40 transition-all group"
            >
              <div className="space-y-4">
                <div className="flex items-center gap-1 text-amber-400">
                  {[...Array(s.rating)].map((_, i) => (
                    <Star key={i} className="size-3.5 fill-amber-400" />
                  ))}
                </div>
                <h3 className="text-lg font-bold font-heading text-foreground">
                  {s.title}
                </h3>
                <p className="text-xs text-muted-foreground italic leading-relaxed font-sans">
                  "{s.quote}"
                </p>
              </div>

              <div className="flex items-center gap-3 pt-4 border-t border-border/60">
                <img
                  src={s.avatar}
                  alt={s.author}
                  className="size-9 rounded-full object-cover border border-border"
                />
                <div>
                  <h4 className="text-xs font-semibold text-foreground">{s.author}</h4>
                  <span className="text-[11px] text-muted-foreground">{s.role}</span>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="p-8 sm:p-12 rounded-3xl liquid-glass border border-cyan-500/30 text-center space-y-6">
          <h2 className="text-3xl sm:text-4xl font-['Instrument_Serif']">
            Share your journeys with the world
          </h2>
          <p className="text-xs sm:text-sm text-muted-foreground max-w-xl mx-auto font-sans">
            Build your travel portfolio and inspire thousands of adventurers around the globe.
          </p>
          <button
            onClick={() => navigate('/create')}
            className="inline-flex items-center gap-2 px-8 py-3.5 bg-cyan-500 hover:bg-cyan-400 text-zinc-950 font-bold text-sm rounded-full transition-all cursor-pointer shadow-lg shadow-cyan-500/20"
          >
            <span>Publish an Itinerary</span>
            <ArrowRight className="size-4" />
          </button>
        </div>
      </div>
    </div>
  );
}
